name: solar-system
  on:
   workflow_dispatch:
   push:
    branches:
      - main
      - 'feature/*'
  jobs: 
      unit-Testing
      runs-on: ubuntu-latest
      steps:
      - name: checout Repository
        uses: actions/checkout@v4
      - name: Setup Nodejs version
        uses: actions/setup-node@v3
        with
          node-version: 18
      - name: Install Dependenices
        run: npm install
      - name: unit Testing
        run: npm test
